name: Pipeline de Validacao

on:
  push:
    branches: [ "main", "master" ]

jobs:
  testes-e-qualidade:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Executar Linting (Ruff)
      run: python -m ruff check .

    - name: Executar Testes Automatizados (Pytest)
      run: python -m pytest